name: Build C++ EXE

on:
  workflow_dispatch:  # Allows manual run from the Actions tab

jobs:
  build:
    runs-on: windows-latest  # Use Windows so we can generate a .exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install g++
      run: |
        choco install mingw -y
        echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH

    - name: Compile C++ code
      run: g++ main.cpp -o matrix_calculator.exe

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: matrix_calculator_exe
        path: matrix_calculator.exe
